CREATE DATABASE taskbd;

CREATE TABLE task(id SERIAL PRIMARY KEY,title VARCHAR(255) UNIQUE,description VARCHAR(255) UNIQUE)

CREATE TABLE task(id SERIAL PRIMARY KEY,title VARCHAR(255) UNIQUE,description VARCHAR(255) UNIQUE)